export const SEARCH_FOOD = 'SEARCH_FOOD';
export const AMOUNT_FOOD_INCREMENT = 'AMOUNT_FOOD_INCREMENT';
export const AMOUNT_FOOD_DECREMENT = 'AMOUNT_FOOD_DECREMENT';
export const PRICE_FILTER_FOOD = 'PRICE_FILTER_FOOD';
export const TYP_FILTER_FOOD = 'TYP_FILTER_FOOD';
export const INGRIDIENTS_FILTER_FOOD = 'INGRIDIENTS_FILTER_FOOD';