export const SEARCH_FOOD = 'SEARCH_FOOD';
export const PRICE_FILTER_FOOD = 'PRICE_FILTER_FOOD';
export const TYP_FILTER_FOOD = 'TYP_FILTER_FOOD';
export const INGRIDIENTS_FILTER_FOOD = 'INGRIDIENTS_FILTER_FOOD';